# This is a basic workflow to help you get started with Actions

name: Server tests & eslint

# Controls when the workflow will run
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "**/package-lock.json"
          cache: "npm"
      - name: Install modules
        run: npm ci
      - name: ESLint check
        run: npm run lint:github
      - name: Tests
        run: npm run test:github
